"""Physics-backend presets for the SO-101 tactile scenes.

Isaac Lab 3.0 picks the physics engine through ``SimulationCfg.physics``.
Everything in this project was built and calibrated on PhysX; the Newton
presets exist so the same scene configs can be brought up on Newton's
MuJoCo-warp solver and, once Newton's own collision pipeline is active, on
SDF hydroelastic contacts (the candidate fix for the point-contact tactile
bottleneck documented in the README).

Preset names
------------
``physx``
    PhysX 5 defaults (what every existing script runs on).
``newton_mjwarp``
    Newton + MuJoCo-warp with MuJoCo's own collision detection.  The
    cheapest way to check that the articulation, drives and cloning survive
    the backend switch.
``newton_pipeline``
    Newton + MuJoCo-warp, contacts generated by Newton's ``CollisionPipeline``
    (rigid contacts).  Exposes per-contact positions, normals and forces
    through ``NewtonManager.get_contacts()``.
``newton_hydro``
    As ``newton_pipeline`` with the SDF hydroelastic contact model enabled.
    Shapes still need the hydroelastic flag and an SDF; see the builder hook
    in :mod:`so101_isaac_lab.newton_hydroelastic` (phase 2).
"""

from __future__ import annotations

from typing import Any

PRESET_NAMES: tuple[str, ...] = (
    "physx",
    "newton_mjwarp",
    "newton_pipeline",
    "newton_hydro",
    "newton_kamino",
    "newton_kamino_pipeline",
    "newton_featherstone_hydro",
    "newton_xpbd",
    "newton_xpbd_hydro",
)

# XPBD (position-based): the one non-MuJoCo Newton solver in this release
# whose ``update_contacts`` writes per-contact forces back, so the tactile
# sensors get data.  Iterations and substeps are raised well above Newton's
# defaults (2 / 1) because the arm's stiff position drives and the
# millimetre-scale pinch need the joint and contact constraints converged.
_XPBD_DEFAULTS: dict[str, Any] = {
    "iterations": 8,
    "rigid_contact_relaxation": 0.9,
    "joint_linear_relaxation": 0.9,
    "joint_angular_relaxation": 0.9,
    "angular_damping": 0.0,
    "enable_restitution": False,
}
_XPBD_SUBSTEPS = 4

# Kamino (P-ADMM, hard frictional contacts), from Isaac Lab's Ant preset.
# ``newton_kamino`` uses Kamino's own detector (up to 8 contacts per pair);
# ``newton_kamino_pipeline`` takes contacts from Newton's CollisionPipeline
# so the hydroelastic generator can be switched on later.
_KAMINO_CONTACT_MAX = 65536

_KAMINO_DEFAULTS: dict[str, Any] = {
    "integrator": "moreau",
    "sparse_jacobian": True,
    "constraints_alpha": 0.1,
    "padmm_max_iterations": 100,
    "padmm_primal_tolerance": 1e-4,
    "padmm_dual_tolerance": 1e-4,
    "padmm_compl_tolerance": 1e-4,
    "padmm_rho_0": 0.05,
    "padmm_eta": 1e-5,
    "padmm_use_acceleration": True,
    "padmm_warmstart_mode": "containers",
    "padmm_contact_warmstart_method": "geom_pair_net_force",
    "padmm_use_graph_conditionals": False,
}

# MuJoCo-warp settings, started from Isaac Lab's Shadow Hand preset (a
# contact-rich grasping task) and kept close to the PhysX setup: one physics
# step per 240 Hz command, implicit-fast integration, elliptic friction cone.
_MJWARP_DEFAULTS: dict[str, Any] = {
    "solver": "newton",
    "integrator": "implicitfast",
    "iterations": 100,
    "ls_iterations": 50,
    "cone": "elliptic",
    "impratio": 10.0,
    "njmax": 300,
    "nconmax": 100,
    "update_data_interval": 1,
}


def make_physics_cfg(name: str, **solver_overrides: Any):
    """Return a concrete ``PhysicsCfg`` for ``name``.

    ``solver_overrides`` are forwarded to ``MJWarpSolverCfg`` for the Newton
    presets (ignored for ``physx``).
    """
    if name not in PRESET_NAMES:
        raise ValueError(f"Unknown physics preset {name!r}; choose from {PRESET_NAMES}")

    if name == "physx":
        from isaaclab_physx.physics import PhysxCfg

        return PhysxCfg()

    from isaaclab_newton.physics.mjwarp_manager_cfg import MJWarpSolverCfg
    from isaaclab_newton.physics.newton_collision_cfg import (
        HydroelasticSDFCfg,
        NewtonCollisionPipelineCfg,
    )
    from isaaclab_newton.physics.newton_manager_cfg import NewtonCfg

    if name.startswith("newton_xpbd"):
        from isaaclab_newton.physics.xpbd_manager_cfg import XPBDSolverCfg

        xpbd_kwargs = dict(_XPBD_DEFAULTS)
        xpbd_kwargs.update(solver_overrides)
        collision_kwargs = {"broad_phase": "explicit", "rigid_contact_max": 32768}
        if name == "newton_xpbd_hydro":
            collision_kwargs["sdf_hydroelastic_config"] = HydroelasticSDFCfg(
                reduce_contacts=True, output_contact_surface=True)
        return NewtonCfg(
            solver_cfg=XPBDSolverCfg(**xpbd_kwargs),
            collision_cfg=NewtonCollisionPipelineCfg(**collision_kwargs),
            num_substeps=_XPBD_SUBSTEPS,
        )

    if name == "newton_featherstone_hydro":
        # Featherstone (articulated-body) solver with penalty contacts: the
        # hydroelastic pressure field acts as an explicit spring (kh x depth x
        # area) instead of being folded into MuJoCo's constraint impedance.
        from isaaclab_newton.physics.featherstone_manager_cfg import FeatherstoneSolverCfg

        return NewtonCfg(
            solver_cfg=FeatherstoneSolverCfg(**solver_overrides),
            collision_cfg=NewtonCollisionPipelineCfg(
                broad_phase="explicit",
                rigid_contact_max=32768,
                sdf_hydroelastic_config=HydroelasticSDFCfg(
                    reduce_contacts=True, output_contact_surface=True),
            ),
            num_substeps=4,
        )

    if name.startswith("newton_kamino"):
        from isaaclab_newton.physics.kamino_manager_cfg import KaminoSolverCfg

        kamino_kwargs = dict(_KAMINO_DEFAULTS)
        kamino_kwargs.update(solver_overrides)
        if name == "newton_kamino":
            return NewtonCfg(
                solver_cfg=KaminoSolverCfg(
                    use_collision_detector=True,
                    collision_detector_pipeline="unified",
                    collision_detector_max_contacts_per_pair=8,
                    **kamino_kwargs,
                ),
                num_substeps=1,
            )
        # Kamino sizes its own contact container (about 9.5k for 4 envs of this
        # scene) and refuses a smaller Newton buffer; give the pipeline room.
        return NewtonCfg(
            solver_cfg=KaminoSolverCfg(use_collision_detector=False, **kamino_kwargs),
            collision_cfg=NewtonCollisionPipelineCfg(
                broad_phase="explicit", rigid_contact_max=int(_KAMINO_CONTACT_MAX)),
            num_substeps=1,
        )

    solver_kwargs = dict(_MJWARP_DEFAULTS)
    solver_kwargs.update(solver_overrides)

    if name == "newton_mjwarp":
        return NewtonCfg(
            solver_cfg=MJWarpSolverCfg(use_mujoco_contacts=True, **solver_kwargs),
            num_substeps=1,
        )

    collision_kwargs: dict[str, Any] = {"broad_phase": "explicit"}
    if name == "newton_hydro":
        # Hydroelastic pairs contribute up to a few hundred reduced contacts
        # each; give both the Newton buffer and MuJoCo's per-world limits room.
        collision_kwargs["sdf_hydroelastic_config"] = HydroelasticSDFCfg(
            reduce_contacts=True,
            output_contact_surface=True,
        )
        collision_kwargs["rigid_contact_max"] = 32768
        solver_kwargs.setdefault("nconmax", 1024)
        solver_kwargs.setdefault("njmax", 4096)
        solver_kwargs["nconmax"] = max(int(solver_kwargs["nconmax"]), 1024)
        solver_kwargs["njmax"] = max(int(solver_kwargs["njmax"]), 4096)
    return NewtonCfg(
        solver_cfg=MJWarpSolverCfg(use_mujoco_contacts=False, **solver_kwargs),
        collision_cfg=NewtonCollisionPipelineCfg(**collision_kwargs),
        num_substeps=1,
    )


def is_newton(name: str) -> bool:
    return name.startswith("newton")
